### ISSUE TITLE
Setup Error. The "template" branch.

### ISSUE THREAD

**Issue by ruden** [haraldpdl/oscommerce#8]
The "template" branch.
Install Step 1
PHP 7.0.13

```
[01-Dec-2016 08:20:41 UTC] PHP Fatal error:  Uncaught TypeError: Argument 5 passed to osCommerce\OM\Core\PDO::initialize() must be of the type integer, string given, called in /home/www/osc-template.loc/osCommerce/OM/Core/Site/Setup/Application/Install/Model/checkDB.php on line 17 and defined in /home/www/osc-template.loc/osCommerce/OM/Core/PDO.php:28
Stack trace:
#0 /home/www/osc-template.loc/osCommerce/OM/Core/Site/Setup/Application/Install/Model/checkDB.php(17): osCommerce\OM\Core\PDO::initialize('localhost', 'uxxxx', 'pxxxx', NULL, '', 'MySQL\\V5')
#1 [internal function]: osCommerce\OM\Core\Site\Setup\Application\Install\Model\checkDB::execute(Array)
#2 /home/www/osc-template.loc/osCommerce/OM/Core/ApplicationModelAbstract.php(19): call_user_func_array(Array, Array)
#3 /home/www/osc-template.loc/osCommerce/OM/Core/Site/Setup/Application/Install/RPC/DBCheck.php(28): osCommerce\OM\Core\ApplicationModelAbstract::__callStatic('checkDB', Array)
#4 [internal function]: osCommerce\OM\Core\Site\Setup\Application\Install\RPC\DBCheck::execute()
#5 /h in /home/www/osc-template.loc/osCommerce/OM/Core/PDO.php on line 28
```

**Comment by ruden** [comment]
Argument 5
php >7.0
?int $port = null
php >5.6
string $port = null
